# 说明：默认注释掉的表示是**非必须的配置**，且给的值都是默认值
address: localhost
mode: debug       # debug, release, test
port: 8972
downloadMaxSize: 1073741824 # 文件下载最大大小


logger:
  level: info
  filename: scrapy.log
  max_size: 100  # MB
  max_age: 0
  max_backups: 30
  FileAndLine: false


swagger: true


