basePath: /api/v1
info:
  contact: {}
  description: This is bigdata SuperAgent.
  title: SuperAgent API Docs
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: 返回ok
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: 健康接口
      tags:
      - Health
swagger: "2.0"
